server:
  port:  8082
  servlet:
    context-path: /



#mybatis配置
mybatis:
  type-aliases-package: com.aaa.mrlang.entity
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml


#提供微服务的名称：对外暴露的为服务的名称
spring:
  application:
    name: provider8082
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test1
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


#eureka相关配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8000/eureka,http://eureka02:8001/eureka
  instance:
    instance-id: provider8082-1


info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$



